### ISSUE TITLE
Submodules private

### ISSUE THREAD

**Issue by advatar** [FhenixProtocol/fheos#97]
Trying to build for the first time but submodules not available:

```
Submodule 'go-ethereum' (git@github.com:FhenixProtocol/go-ethereum.git) registered for path 'go-ethereum'
Submodule 'warp-drive' (git@github.com:FhenixProtocol/warp-drive.git) registered for path 'warp-drive'

```

**Comment by Cashmaney** [comment]
Hey @advatar!

Right now a few of our repos are still private while we're tinkering with things in preparation of our upcoming testnet. I hope we'll be able to open-source everything soon so it's easier to build (also for us! Private repos are pretty annoying 😅).

In the meantime, if you don't mind sharing (here or reaching out via discord/DM/email) what you're looking to do, we might be able to share the repos with you privately.

Apologies for the trouble!

**Comment by Cashmaney** [comment]
Not 100% sure if you're referring to tfhe-rs or a different lib/scheme, but I invited you to the relevant repos, so you can give it a spin
